package gov.gujarat.rnb.infratrack.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/** Relational schema for InfraTrack. */
public final class Schema {
    private Schema() {}

    public static final String[] TABLES = {
        """
        CREATE TABLE regions (
          id INT PRIMARY KEY, code VARCHAR(8) UNIQUE NOT NULL, name VARCHAR(80) NOT NULL,
          circle_name VARCHAR(120) NOT NULL, lat DOUBLE, lng DOUBLE, is_focus BOOLEAN DEFAULT TRUE)""",
        """
        CREATE TABLE divisions (
          id INT PRIMARY KEY, code VARCHAR(12) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL,
          region_id INT NOT NULL REFERENCES regions(id), lat DOUBLE, lng DOUBLE)""",
        """
        CREATE TABLE subdivisions (
          id INT PRIMARY KEY, code VARCHAR(16) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL,
          division_id INT NOT NULL REFERENCES divisions(id), region_id INT NOT NULL REFERENCES regions(id),
          lat DOUBLE, lng DOUBLE)""",
        """
        CREATE TABLE assets (
          id INT PRIMARY KEY, asset_code VARCHAR(24) UNIQUE NOT NULL, name VARCHAR(200) NOT NULL,
          asset_type VARCHAR(16) NOT NULL, category VARCHAR(60) NOT NULL,
          region_id INT NOT NULL REFERENCES regions(id), division_id INT NOT NULL REFERENCES divisions(id),
          subdivision_id INT NOT NULL REFERENCES subdivisions(id),
          lat DOUBLE, lng DOUBLE, year_built INT, condition_score DOUBLE, condition VARCHAR(10),
          status VARCHAR(20) DEFAULT 'operational', last_inspection_date DATE, next_maintenance_date DATE,
          length_km DOUBLE, span_m DOUBLE, floors INT, traffic_aadt INT DEFAULT 0,
          replacement_value_cr DOUBLE, risk_score DOUBLE)""",
        """
        CREATE TABLE inspections (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, asset_id INT NOT NULL REFERENCES assets(id),
          date DATE, inspector VARCHAR(100), condition_score DOUBLE, defects VARCHAR(300) DEFAULT '',
          action VARCHAR(30) DEFAULT 'routine', remarks VARCHAR(2000) DEFAULT '')""",
        """
        CREATE TABLE contractors (
          id INT PRIMARY KEY, name VARCHAR(150), registration_no VARCHAR(40), contractor_class VARCHAR(10), rating DOUBLE)""",
        """
        CREATE TABLE projects (
          id INT PRIMARY KEY, code VARCHAR(24) UNIQUE NOT NULL, name VARCHAR(250) NOT NULL,
          work_type VARCHAR(30), scheme VARCHAR(60), asset_id INT REFERENCES assets(id),
          region_id INT NOT NULL, division_id INT NOT NULL, subdivision_id INT NOT NULL,
          contractor_id INT REFERENCES contractors(id), sanctioned_cost_cr DOUBLE, expenditure_cr DOUBLE DEFAULT 0,
          physical_progress DOUBLE DEFAULT 0, start_date DATE, target_date DATE, status VARCHAR(20),
          is_delayed BOOLEAN DEFAULT FALSE)""",
        """
        CREATE TABLE progress_updates (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id INT NOT NULL REFERENCES projects(id),
          date DATE, physical_progress DOUBLE, remarks VARCHAR(2000) DEFAULT '', submitted_by VARCHAR(160))""",
        """
        CREATE TABLE bills (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id INT NOT NULL REFERENCES projects(id),
          bill_no VARCHAR(20), amount_lakh DOUBLE, submitted_on DATE, status VARCHAR(12), remarks VARCHAR(2000) DEFAULT '')""",
        """
        CREATE TABLE users (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(120) UNIQUE NOT NULL,
          name VARCHAR(100), designation VARCHAR(120), password_hash VARCHAR(200), role VARCHAR(30),
          region_id INT, division_id INT, subdivision_id INT, contractor_id INT)""",
        """
        CREATE TABLE complaints (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ticket VARCHAR(24) UNIQUE NOT NULL,
          category VARCHAR(40), description VARCHAR(2000), location_text VARCHAR(200), lat DOUBLE, lng DOUBLE,
          region_id INT NOT NULL, division_id INT NOT NULL, subdivision_id INT NOT NULL,
          citizen_name VARCHAR(100), phone VARCHAR(20) DEFAULT '', user_id INT REFERENCES users(id),
          priority VARCHAR(10), status VARCHAR(15), resolution_note VARCHAR(2000) DEFAULT '',
          created_at TIMESTAMP, updated_at TIMESTAMP)""",
        """
        CREATE TABLE audit_logs (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts TIMESTAMP, user_name VARCHAR(120),
          action VARCHAR(60), entity VARCHAR(30), entity_id VARCHAR(30), detail VARCHAR(2000) DEFAULT '', region_id INT)""",
    };

    public static final String[] INDEXES = {
        "CREATE INDEX ix_assets_region ON assets(region_id)",
        "CREATE INDEX ix_assets_division ON assets(division_id)",
        "CREATE INDEX ix_assets_sub ON assets(subdivision_id)",
        "CREATE INDEX ix_assets_type ON assets(asset_type)",
        "CREATE INDEX ix_assets_cond ON assets(condition)",
        "CREATE INDEX ix_assets_due ON assets(next_maintenance_date)",
        "CREATE INDEX ix_assets_risk ON assets(risk_score)",
        "CREATE INDEX ix_insp_asset ON inspections(asset_id)",
        "CREATE INDEX ix_proj_region ON projects(region_id)",
        "CREATE INDEX ix_proj_division ON projects(division_id)",
        "CREATE INDEX ix_proj_sub ON projects(subdivision_id)",
        "CREATE INDEX ix_proj_status ON projects(status)",
        "CREATE INDEX ix_proj_contractor ON projects(contractor_id)",
        "CREATE INDEX ix_proj_asset ON projects(asset_id)",
        "CREATE INDEX ix_upd_project ON progress_updates(project_id)",
        "CREATE INDEX ix_bill_project ON bills(project_id)",
        "CREATE INDEX ix_comp_region ON complaints(region_id)",
        "CREATE INDEX ix_comp_division ON complaints(division_id)",
        "CREATE INDEX ix_comp_sub ON complaints(subdivision_id)",
        "CREATE INDEX ix_comp_status ON complaints(status)",
        "CREATE INDEX ix_audit_ts ON audit_logs(ts)",
    };

    public static void recreate(Connection c) throws SQLException {
        try (Statement st = c.createStatement()) {
            st.execute("DROP ALL OBJECTS");
            for (String t : TABLES) st.execute(t);
            for (String ix : INDEXES) st.execute(ix);
        }
    }

    public static boolean exists() {
        Object n = Db.scalar("SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ASSETS'");
        return n != null && ((Number) n).longValue() > 0;
    }
}
